In [1]:
from PIL import Image
import face_recognition

In [2]:
# 将jpg文件加载到numpy数组中
image = face_recognition.load_image_file("../image/people.jpg")
print(image)

[[[ 32  42  44]
  [ 32  42  44]
  [ 32  42  44]
  ...
  [ 26  31  37]
  [ 25  30  36]
  [ 24  29  35]]

 [[ 31  41  43]
  [ 31  41  43]
  [ 31  41  43]
  ...
  [ 20  25  31]
  [ 19  24  30]
  [ 19  24  30]]

 [[ 34  44  46]
  [ 34  44  46]
  [ 34  44  46]
  ...
  [ 17  22  28]
  [ 16  21  27]
  [ 16  21  27]]

 ...

 [[ 41  53  65]
  [ 49  62  71]
  [ 40  49  58]
  ...
  [ 58  58  66]
  [ 58  58  66]
  [ 59  59  67]]

 [[ 29  42  51]
  [ 31  44  52]
  [ 38  47  54]
  ...
  [ 39  40  45]
  [ 38  39  44]
  [ 41  42  47]]

 [[ 86  99 107]
  [ 87 100 106]
  [ 94 103 110]
  ...
  [ 97  98 103]
  [ 97  98 103]
  [ 99 100 105]]]


In [3]:
# 使用默认的基于HOG的模型查找图像中的所有面
# 这种方法相当准确，但不如CNN模型准确，也没有GPU加速

# 在图片中查找所有面孔
face_locations = face_recognition.face_locations(image)
print(face_locations)
print("我在这张照片中找到了{}个面孔".format(len(face_locations)))

[(36, 93, 79, 50), (66, 149, 102, 113)]
我在这张照片中找到了2个面孔


In [4]:
for face_location in face_locations:
    #  打印此图像中每张脸的位置
    top, right, bottom, left = face_location
    print("面部位于像素位置 top：{}, left：{}, bottom： {}, right：{}".format(top, left, bottom, right))
    
    #  您可以像这样访问实际面部
    #     array转换成image
    face_image = image[top: bottom, left: right]
    pil_image = Image.fromarray(face_image)
    pil_image.show()

面部位于像素位置 top：36, left：50, bottom： 79, right：93
面部位于像素位置 top：66, left：113, bottom： 102, right：149
