### 2.1 学习数据网站：
&nbsp;&nbsp;sklearn  kaggle  UCI

### 2.2 sklearn数据集  
sklearn.datasets  
&nbsp;&nbsp;load_*：获取小规模的数据集  
&nbsp;&nbsp;fetch_*：获取大规模的数据集  
    
   2    sklearn小数据集：  
&nbsp;&nbsp;sklearn.datasets.load_iris()  
   3    sklearn大数据集  
&nbsp;&nbsp;sklearn.datasets.fetch_20newsgroups(参数)  
   4    数据集的返回值  
&nbsp;&nbsp;datasets.base.Bunch(继承自字典)  
&nbsp;&nbsp; dict["key"] = values
&nbsp;&nbsp;bunch.key = values

In [20]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

def datasets_demo():
    """
    sklearn数据集使用
    return
    """
    #   获取数据集
    iris = load_iris()
    print("鸢尾花数据集：\n", iris)
    print("查看数据集描述：\n", iris["DESCR"])
    print("查看特征值名字：\n", iris.feature_names)
    print("查看特征值：\n", iris.data.shape)
    
    #  数据集划分
    x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=22)
    print("训练集的特征值：\n", x_train, x_train.shape)
    
    return None

if __name__ == "__main__":
    #   sklearn数据集使用
    datasets_demo()


鸢尾花数据集：
 {'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### 2.3 数据集的划分
&nbsp;&nbsp; 训练数据：用于训练，构建模型  
&nbsp;&nbsp; 测试数据：在模型检验时使用，用于评估模型是否有效    测试集20%-30%  
&nbsp;&nbsp; 训练集特征值，测试集特征值，训练集目标值，测试集目标值  
&nbsp;&nbsp; x_train, x_test, y_train, y_test

### 2.4 特征工程介绍
&nbsp;&nbsp;算法：特征工程  
&nbsp;&nbsp;sklearn:特征工程  
&nbsp;&nbsp;pandas   数据清洗， 数据处理  
&nbsp;&nbsp;  特征抽取/特征提取  
&nbsp;&nbsp;  &nbsp;&nbsp;   机器学习算法 - 统计方法 - 数学公式  
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; 文本类型 =》数值  
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; 类型 -》数值  
&nbsp;&nbsp;  特征值处理  
&nbsp;&nbsp;  特征降维

### 2.5特征提取
sklearn.feature.extraction  
#### 1 字典特征提取 - 类别 =》one-hot编码  
&nbsp;&nbsp; sklearn.feature.extraction.DictVectorizer(sparse=True)    vector 向量   矩阵(matrix，二维数组)  
&nbsp;&nbsp; &nbsp;&nbsp;  返回sparse矩阵
&nbsp;&nbsp; sparse稀疏矩阵  将非零值按位置表示出来      节省内存-提高加载效率
&nbsp;&nbsp; 应用场景：  
&nbsp;&nbsp; &nbsp;&nbsp;1） 数据集当中类别特征比较多  
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; 将数据特征 -》字典特征  
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; DictVctorizer转换  
&nbsp;&nbsp; &nbsp;&nbsp;2）本身拿到的数据就是字典类型  
#### 2 文本特征提取
&nbsp;&nbsp;  单词 作为 特征
&nbsp;&nbsp;  特征：特征词
&nbsp;&nbsp;方法一： CountVectorizer
&nbsp;&nbsp;&nbsp;&nbsp;统计每个样本特征值出现的次数
&nbsp;&nbsp;&nbsp;&nbsp;stop_words:停用的  停用词表

In [15]:
from sklearn.feature_extraction import DictVectorizer
def dict_demo():
    """
    字典特征提取
    """
    data = [
        {'city': '北京', 'temperature': 100},
        {'city': '上海', 'temperature': 60},
        {'city': '深圳', 'temperature': 30}
    ]
    #  1、实例化一个转换器
    trander = DictVectorizer(sparse=True)   #或者直接为sparse=False data_new不用加.toarray()
    #  2、调用fit_transform()
    data_new = trander.fit_transform(data)
    print('data_new:\n', data_new.toarray())
    print('特征名字：\n', trander.get_feature_names())
    return None
dict_demo()

data_new:
 [[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]
特征名字：
 ['city=上海', 'city=北京', 'city=深圳', 'temperature']


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
def count_demo():
    """
    文本特征抽取: CountVectorizer
    """
    data = ['life is short, i like like python', 'life is too long, i dislike %%python']
    #  1、实例化一个转换器类
    transfer = CountVectorizer()
    #  2、调用fit_transform()
    data_new = transfer.fit_transform(data)
    print('data_newata:\n', data_new.toarray())
    print('特征名字：\n', transfer.get_feature_names())
    return None
count_demo()

data_newata:
 [[0 1 1 2 0 1 1 0]
 [1 1 1 0 1 1 0 1]]
特征名字：
 ['dislike', 'is', 'life', 'like', 'long', 'python', 'short', 'too']


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
def count_chinese_demo():
    """
    文本特征抽取: CountVectorizer
    """
    data = ['我 爱 北京 天安门', '天安门 上 太阳升']   #中文要用空格进行分词
    #  1、实例化一个转换器类
    transfer = CountVectorizer()
    #  2、调用fit_transform()
    data_new = transfer.fit_transform(data)
    print('data_newata:\n', data_new.toarray())
    print('特征名字：\n', transfer.get_feature_names())
    return None
count_chinese_demo()

data_newata:
 [[1 1 0]
 [0 1 1]]
特征名字：
 ['北京', '天安门', '太阳升']


In [7]:
from sklearn.feature_extraction.text import CountVectorizer
import jieba
def cut_word(text):
    """
    进行中文分词
    """
    print("".join(list(jieba.cut(text))))
# def count_chinese_demo2():
#     """
#     文本特征抽取: CountVectorizer
#     """
#     # 将中文文本进行分词
#     data = ['我不知道自己是否爱唱戏', '我出身梨园世家','5岁开始学艺', '我想我是没有选择权的',
#             '既然做了就要做好','于是我7岁登台','12岁开始公演','或许是家庭的氛围','亦或是我自己的努力',
#             '我14岁已经在上海滩声名鹊起','家喻户晓了', '人的欲望是无穷尽的','我不再满足于一个小小的上海滩',
#             '于是18岁那年','为了唱响京城','心高气傲的我亦然选择了北上','殊不知一场命运的浩劫在前方静悄悄地等待着我']   
#     #中文要用空格进行分词
#     data_new = []
#     for sent in data:
#         data_new(cut_word(sent))
#     print(data_new)
#     #  1、实例化一个转换器类
#     transfer = CountVectorizer()
#     #  2、调用fit_transform()
#     data_final = transfer.fit_transform(data_new)
#     print('data_newata:\n', data_final.toarray())
#     print('特征名字：\n', transfer.get_feature_names())
#     return None
# count_chinese_demo2()
data = ['我不知道自己是否爱唱戏',
            '我14岁已经在上海滩声名鹊起',
            '殊不知一场命运的浩劫在前方静悄悄地等待着我']   
for i in data:
    cut_word(i)

我不知道自己是否爱唱戏
我14岁已经在上海滩声名鹊起
殊不知一场命运的浩劫在前方静悄悄地等待着我
